### ISSUE TITLE
Remove "Weight" attribute during assignment creation

### ISSUE THREAD

**Issue by drwlodarski** [gamification-survey-platform/server#100]
Every assignment has a mandatory attribute "Weight" which was meant to indicate the % of total course grade. Given that other course data is not stored in the platform, it makes no sense to keep it. The refactoring should also include data model update.

<img width="673" alt="image" src="https://github.com/gamification-survey-platform/server/assets/111450974/de43308d-421a-48ef-bbed-79b2cc441c83">

**Comment by hanqidS2023** [comment]
Solved as https://github.com/gamification-survey-platform/server/commit/3b5b784756be8bd85f8b91ab7c01d3974ae656a2
