### ISSUE TITLE
An error when trying to edit an existing course

### ISSUE THREAD

**Issue by drwlodarski** [gamification-survey-platform/server#52]
When trying to update a course's syllabus and semester, an error persists.

![Image](https://user-images.githubusercontent.com/111450974/269417976-c3190f5f-80e6-451a-b870-e0f4c17d0908.png)

**Comment by xinyuew3S2024** [comment]
It should be working now when you click edit(save) button:

https://github.com/gamification-survey-platform/server/assets/156377697/f232a9e8-0a15-4591-956a-6977509111e3

**Comment by rhuang4F2023** [comment]
Thank you for fixing this. We should now be able to edit the course information as expected without encountering any errors.
