### ISSUE TITLE
Cannot upload profile

### ISSUE THREAD

**Issue by rhuang4F2023** [gamification-survey-platform/server#76]
<img width="812" alt="Screenshot 2024-02-06 at 10 16 59 AM" src="https://github.com/gamification-survey-platform/server/assets/143446333/07cf8394-1526-46e6-8dd8-8b0919915c29">

**Comment by xinyuew3S2024** [comment]
The platform now supports profile image uploads:

<img width="1111" alt="Screenshot 2024-02-16 at 8 53 57 PM" src="https://github.com/gamification-survey-platform/server/assets/156377697/806f1317-9c10-45ef-8a6a-f276a98b8cb4">

**Comment by rhuang4F2023** [comment]
<img width="1106" alt="Screenshot 2024-02-17 at 3 20 20 PM" src="https://github.com/gamification-survey-platform/server/assets/143446333/5bb17aa5-09ec-43d7-bf12-5c1f51e2e4e0">
Indeed, thank you Xinyue!
