### ISSUE TITLE
 Inability to Edit Surveys After Publishing - Changes Disappear After Refresh

### ISSUE THREAD

**Issue by rhuang4F2023** [gamification-survey-platform/server#79]
While working on resolving issue #58, I encountered a problem related to the survey editing functionality. Once a survey is published, it appears that any edits made to the survey—including adding new sections or questions—are not being saved properly. Although these changes seem to apply immediately, they disappear upon refreshing the page, indicating that the changes are not being persisted.

Steps to Reproduce
Publish a survey.
Attempt to edit the survey by adding a new section or question.
Observe that the changes appear to be applied initially.
Refresh the page.

**Comment by xinyuew3S2024** [comment]
Hi Terry, I tested it locally and found that the "save survey" operation takes a while (about 5-10 seconds). After saving successfully, the page will automatically redirect to the Assignment section. Perhaps you refreshed the page and didn't wait for the operation to complete after clicking the "save survey" button?

**Comment by rhuang4F2023** [comment]
Hi Xinyue,

Not a bug now. Thank you for your update and for looking into this. I'll ensure to wait for the operation to complete before refreshing the page next time.
